name: Recovery Build (Legacy) - ubuntu:14.04 docker

on:
  push:
    branches:
      - main

env:
  MANIFEST_URL: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni'
  MANIFEST_BRANCH: 'twrp-4.4-deprecated'
  DEVICE_TREE_URL: 'https://github.com/coara-chocomaru/SH06D-twrp'
  DEVICE_TREE_BRANCH: 'main'
  DEVICE_PATH: 'device/shrp/sh06d'
  DEVICE_NAME: 'sh06d'
  MAKEFILE_NAME: 'omni_sh06d'
  BUILD_TARGET: 'recovery'
  JAVA_VERSION: '6'

jobs:
  build-14-04:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository (host)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show parameters
        run: |
          echo "Manifest URL: ${{ env.MANIFEST_URL }}"
          echo "Device Tree URL: ${{ env.DEVICE_TREE_URL }}"
          echo "Device Path: ${{ env.DEVICE_PATH }}"
          echo "Device Name: ${{ env.DEVICE_NAME }}"

      - name: Ensure ubuntu:14.04 image is available
        run: docker pull ubuntu:14.04

      - name: Create containerized build script (host)
        run: |
          cat > "${{ github.workspace }}/build.sh" <<'EOF'
          #!/bin/bash
          set -euo pipefail
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install openjdk-6-jdk gperf gcc-multilib g++-multilib libc6-dev wget curl tar lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z1-dev git libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-gplv2-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk2.8-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libreadline-gplv2-dev libstdc++-4.8-dev libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev python2.7
          cd ~
          sudo wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
          sudo tar xzf Python-3.6.4.tgz
          cd Python-3.6.4
          sudo ./configure --enable-optimizations
          sudo make altinstall
          sudo ln -s /usr/local/bin/python3.6 /usr/bin/python3.6
          sudo -H pip3.6 install --upgrade pip
          cd /
          mkdir -p /root/bin
          curl -sSfL https://github.com/coara-chocomaru/setappops/releases/download/%E4%BF%9D%E7%AE%A1%E7%94%A8%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9/repo -o /root/bin/repo
          chmod a+x /root/bin/repo
          export PATH=/root/bin:$PATH
          ln -sf /usr/local/python3.6 /usr/bin/python
          mkdir -p /workspace
          cd /workspace
          MANIFEST_URL="${MANIFEST_URL}"
          MANIFEST_BRANCH="${MANIFEST_BRANCH}"
          DEVICE_TREE_URL="${DEVICE_TREE_URL}"
          DEVICE_TREE_BRANCH="${DEVICE_TREE_BRANCH}"
          DEVICE_PATH="${DEVICE_PATH}"
          DEVICE_NAME="${DEVICE_NAME}"
          MAKEFILE_NAME="${MAKEFILE_NAME}"
          BUILD_TARGET="${BUILD_TARGET}"
          JAVA_VERSION="${JAVA_VERSION}"
          echo "Starting build inside container..."
          echo "MANIFEST_URL=${MANIFEST_URL}"
          echo "DEVICE_PATH=${DEVICE_PATH}"
          echo "DEVICE_NAME=${DEVICE_NAME}"
          sed -i 's|archive.ubuntu.com|old-releases.ubuntu.com|g' /etc/apt/sources.list || true
          sed -i 's|security.ubuntu.com|old-releases.ubuntu.com|g' /etc/apt/sources.list || true
          git config --global user.name 'azwhikaru' || true
          git config --global user.email 'azwhikaru+37921907@github.com' || true
          export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64 || true
          export PATH="$JAVA_HOME/bin:$PATH"
          python3 /root/bin/repo init --depth=1 -u "${MANIFEST_URL}" -b "${MANIFEST_BRANCH}"
          python3 /root/bin/repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          TARGET_DIR="/workspace/${DEVICE_PATH}"
          mkdir -p "$(dirname "$TARGET_DIR")"
          if [ -d "$TARGET_DIR" ] && [ -n "$(ls -A $TARGET_DIR 2>/dev/null)" ]; then
            mv "$TARGET_DIR" "${TARGET_DIR}.bak.$(date +%s)" || true
          fi
          git clone --depth=1 -b "${DEVICE_TREE_BRANCH}" "${DEVICE_TREE_URL}" "$TARGET_DIR" || true
          if [ ! -f /swapfile ]; then
            set +e
            if command -v fallocate >/dev/null 2>&1; then
              fallocate -l 12G /swapfile || true
            fi
            if [ ! -s /swapfile ]; then
              dd if=/dev/zero of=/swapfile bs=1M count=12288 status=none || true
            fi
            chmod 600 /swapfile || true
            SWAP_OK=0
            if mkswap /swapfile >/dev/null 2>&1; then
              if swapon /swapfile >/dev/null 2>&1; then
                SWAP_OK=1
              fi
            fi
            if [ "$SWAP_OK" -ne 1 ]; then
              if command -v losetup >/dev/null 2>&1; then
                LOOPDEV=$(losetup --find --show /swapfile 2>/dev/null || true)
                if [ -n "$LOOPDEV" ]; then
                  if mkswap "$LOOPDEV" >/dev/null 2>&1 && swapon "$LOOPDEV" >/dev/null 2>&1; then
                    SWAP_OK=1
                  fi
                fi
              fi
            fi
            if [ "$SWAP_OK" -eq 1 ]; then
              echo '/swapfile none swap sw 0 0' >> /etc/fstab || true
            else
              echo "Warning: swap setup failed, continuing without swap"
            fi
            set -e
          export ALLOW_MISSING_DEPENDENCIES=true
          export PYTHON=python2.7
          export LC_ALL=C
          if [ -f build/envsetup.sh ]; then
            set +u
            export PYTHON=python2.7
            source build/envsetup.sh
            set -u
            lunch "${MAKEFILE_NAME}-eng" || true
            export PYTHON=python2.7
            make clean || true
            make -j$(nproc --all) "${BUILD_TARGET}" || true
          else
            echo "ERROR: build/envsetup.sh not found. repo init/sync may have failed."
            exit 1
          fi
          echo "Build finished inside container. Artifacts should be in /workspace/out/target/product/${DEVICE_NAME}"
          ls -la /workspace/out/target/product/${DEVICE_NAME} || true
          EOF
          chmod +x "${{ github.workspace }}/build.sh"

      - name: Run build inside ubuntu:14.04 container (docker)
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            -e MANIFEST_URL="${{ env.MANIFEST_URL }}" \
            -e MANIFEST_BRANCH="${{ env.MANIFEST_BRANCH }}" \
            -e DEVICE_TREE_URL="${{ env.DEVICE_TREE_URL }}" \
            -e DEVICE_TREE_BRANCH="${{ env.DEVICE_TREE_BRANCH }}" \
            -e DEVICE_PATH="${{ env.DEVICE_PATH }}" \
            -e DEVICE_NAME="${{ env.DEVICE_NAME }}" \
            -e MAKEFILE_NAME="${{ env.MAKEFILE_NAME }}" \
            -e BUILD_TARGET="${{ env.BUILD_TARGET }}" \
            -e JAVA_VERSION="${{ env.JAVA_VERSION }}" \
            ubuntu:14.04 /bin/bash -c "/workspace/build.sh"

      - name: List artifacts on host (sanity)
        run: |
          echo "Artifacts (host view):"
          ls -la "${{ github.workspace }}/out/target/product/${{ env.DEVICE_NAME }}" || true

      - name: Create GitHub Release and upload artifacts (host)
        if: always()
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/target/product/${{ env.DEVICE_NAME }}/*.zip
            out/target/product/${{ env.DEVICE_NAME }}/*.img
            out/target/product/${{ env.DEVICE_NAME }}/*vendor*.img
          name: ${{ env.DEVICE_NAME }}-android5-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ env.MANIFEST_BRANCH }}
            Device: ${{ env.DEVICE_NAME }}
            Target: ${{ env.BUILD_TARGET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
